"""empty message

Revision ID: b90dd33f99cd
Revises: c6755a405fe1
Create Date: 2023-12-18 01:44:04.926745

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b90dd33f99cd'
down_revision = 'c6755a405fe1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('security_db', schema=None) as batch_op:
        batch_op.alter_column('goods_name',
               existing_type=mysql.TEXT(),
               type_=sa.String(length=128),
               existing_comment='产品名称',
               existing_nullable=True)
        batch_op.alter_column('security_code',
               existing_type=mysql.VARCHAR(length=64),
               type_=sa.String(length=24),
               existing_comment='防伪码',
               existing_nullable=True)
        batch_op.alter_column('production_time',
               existing_type=mysql.VARCHAR(length=64),
               type_=sa.DateTime(),
               existing_comment='生产时间',
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('security_db', schema=None) as batch_op:
        batch_op.alter_column('production_time',
               existing_type=sa.DateTime(),
               type_=mysql.VARCHAR(length=64),
               existing_comment='生产时间',
               existing_nullable=True)
        batch_op.alter_column('security_code',
               existing_type=sa.String(length=24),
               type_=mysql.VARCHAR(length=64),
               existing_comment='防伪码',
               existing_nullable=True)
        batch_op.alter_column('goods_name',
               existing_type=sa.String(length=128),
               type_=mysql.TEXT(),
               existing_comment='产品名称',
               existing_nullable=True)

    # ### end Alembic commands ###
