"""empty message

Revision ID: c6755a405fe1
Revises: 
Create Date: 2023-12-18 00:33:14.305173

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c6755a405fe1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('security_db',
    sa.Column('goods_name', sa.Text(), nullable=True, comment='产品名称'),
    sa.Column('security_code', sa.String(length=64), nullable=True, comment='防伪码'),
    sa.Column('production_time', sa.String(length=64), nullable=True, comment='生产时间'),
    sa.Column('queries_num', sa.Integer(), nullable=True, comment='查询次数'),
    sa.Column('id', sa.Integer(), nullable=False, comment='id主键'),
    sa.Column('add_time', sa.DateTime(), nullable=True, comment='创建时间'),
    sa.Column('upd_time', sa.DateTime(), nullable=True, comment='更新时间'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('security_db')
    # ### end Alembic commands ###
